### ISSUE TITLE
Converting STL to PNG error on windows 7

### ISSUE THREAD

**Issue by nielran** [cubehero/stljs#3]
Hi,

I am trying to test the example that you provide in the readme about convert a stl to a png , but I am not able to make it work. 

I have installed pov-ray for windows, version 3.6, but when i run the script I get the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

I've noticed that in the readme, when you talk about pov-ray, only talk about Linux and Mac OSX, but not about Windows. It is no prepare for windows systems, or I have something misconfigured?

Thanks in advance for your response.

**Comment by jvdonk** [comment]
The code isn't cross platform for windows because of:

1) Filesystem code(paths)
2) PovRay on windows isn't using a povray executable but pvengine64 (on 64bit windows)
3) In PovRay 3.7 the -s switch isn't recognized (if it's for automatically closing when ready, replace it with /EXIT

So:
1) Refactor the paths related code in lib\to\image.js see [writing cross platform code in nodejs](https://shapeshed.com/writing-cross-platform-node/)
2/3) In lib\to\image.js, instead of 
```
.spawn('povray', ["-s",...
```
use
```
.spawn('pvengine64', ["/EXIT",...
```
